# This is a basic workflow to help you get started with Actions

name: wdaqs-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
      - master
      -  dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: SetUp NuGet
    - uses: warrenbuckley/Setup-NuGet@v1
    - name: Restore Packages
      run: nuget restore wdaqs.sln
    - name: SetUp MSBuild.exe
      uses: warrenbuckley/SetUp-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild wdaqs.sln -p:Configuration=Release
